# Generated by Django 5.0 on 2026-06-04 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('costCenter', models.CharField(max_length=50, verbose_name='Centro de Costo')),
                ('projectNumber', models.CharField(max_length=50, verbose_name='Número de Proyecto')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('area', models.CharField(max_length=255)),
                ('areaType', models.CharField(choices=[('facultad', 'Facultad'), ('centro_investigacion', 'Centro de Investigación'), ('departamento', 'Departamento'), ('direccion', 'Dirección'), ('unidad', 'Unidad'), ('otro', 'Otro')], default='facultad', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'En pausa'), ('completed', 'Completado')], default='active', max_length=20)),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('renewalDate', models.DateField(blank=True, null=True, verbose_name='Fecha de Renovación')),
                ('budgetPeriod', models.CharField(blank=True, max_length=20, null=True, verbose_name='Período Presupuestario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
                'unique_together': {('costCenter', 'projectNumber')},
            },
        ),
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period', models.CharField(max_length=20)),
                ('periodEnd', models.DateField()),
                ('syncedAt', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_history', to='projects.project')),
            ],
            options={
                'verbose_name': 'Historial de Presupuesto',
                'verbose_name_plural': 'Historiales de Presupuesto',
                'ordering': ['-syncedAt'],
            },
        ),
    ]
