# Generated by Django 5.0 on 2026-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conectividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioconectividad',
            name='email',
            field=models.EmailField(blank=True, default='no-reply@uh.cu', max_length=254, null=True),
        ),
    ]
