# Generated by Django 5.0 on 2026-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area_type', models.CharField(choices=[('facultad', 'Facultad'), ('centro_investigacion', 'Centro de Investigación'), ('departamento', 'Departamento'), ('direccion', 'Dirección'), ('unidad', 'Unidad'), ('otro', 'Otro')], max_length=30)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['area_type', 'name'],
                'unique_together': {('name', 'area_type')},
            },
        ),
    ]
