# Generated by Django 5.0 on 2026-06-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('businessType', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('dataType', models.CharField(choices=[('products', 'Productos'), ('services', 'Servicios'), ('both', 'Ambos')], default='both', max_length=20)),
                ('data', models.JSONField(default=list)),
                ('contractActive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['-created_at'],
            },
        ),
    ]
