# Generated by Django 5.0 on 2026-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_empresa_pedidoextra_producto_servicio_delete_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contactos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda',
            field=models.CharField(default='CUP', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_negocio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
